spring.sql.init.mode=always
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DATABASE_TO_UPPER=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=password
# Optional: Enable H2 Console (requires WebFlux)
spring.h2.console.enabled=true